# Generated by Django 5.0.1 on 2024-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.TextField(null=True),
        ),
    ]
